export const Roles = {
  HR: 'HR',
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
  SUBADMIN: 'SUB-ADMIN',
  OUTLETADMIN: 'OUTLET-ADMIN',
  OUTLETSUBADMIN: 'OUTLET-SUB-ADMIN',
  INVENTORYMANAGER: 'INVENTORY-MANAGER',
  EMPLOYEE: 'EMPLOYEE'
};
